# Generated by Django 3.2.9 on 2021-11-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=200)),
                ('send_date', models.DateTimeField()),
            ],
        ),
    ]
